### PR TITLE
Add service account layer

### PR DESCRIPTION
**Pull request by digitalrane**
Moved user and group creation to layer-service-account, added layer-service-account.

### CODE REVIEW

**Comment by chris-sanders** [comment]
I didn't even notice this review, were you done with it and ready to merge? I didn't get an email so didn't notice it was here. I hope MR #4 doesn't conflict to much with this although I suspect it won't be hard to work out since it's mostly moving files.

**Comment by digitalrane** [comment]
I'll rebase this one shortly, likely just needs path updates to match the `src` directory changes

**Comment by digitalrane** [comment]
Rebased and tests are all passing locally, please verify in your env though given the nature of the changes

**Comment by chris-sanders** [comment]
I'm getting the following error deploying via JAAS.

`unit-radarr-xenial-local-0: 00:35:28 ERROR unit.radarr-xenial-local/0.juju-log Hook error:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-radarr-xenial-local-0/.venv/lib/python3.5/site-packages/charms/reactive/__init__.py", line 73, in main
    bus.dispatch(restricted=restricted_mode)
  File "/var/lib/juju/agents/unit-radarr-xenial-local-0/.venv/lib/python3.5/site-packages/charms/reactive/bus.py", line 390, in dispatch
    _invoke(other_handlers)
  File "/var/lib/juju/agents/unit-radarr-xenial-local-0/.venv/lib/python3.5/site-packages/charms/reactive/bus.py", line 359, in _invoke
    handler.invoke()
  File "/var/lib/juju/agents/unit-radarr-xenial-local-0/.venv/lib/python3.5/site-packages/charms/reactive/bus.py", line 181, in invoke
    self._action(*args)
  File "/var/lib/juju/agents/unit-radarr-xenial-local-0/charm/reactive/radarr.py", line 31, in install_radarr
    radarr.install_radarr()
  File "lib/lib_radarr.py", line 216, in install_radarr
    self.update_radarr()
  File "lib/lib_radarr.py", line 194, in update_radarr
    self.configure_installdir()
  File "lib/lib_radarr.py", line 178, in configure_installdir
    self.user, chowntopdir=True)
  File "/var/lib/juju/agents/unit-radarr-xenial-local-0/.venv/lib/python3.5/site-packages/charmhelpers/core/host.py", line 908, in chownr
    gid = grp.getgrnam(group).gr_gid
KeyError: 'getgrnam(): name not found: radarr'

unit-radarr-xenial-local-0: 00:35:28 ERROR juju.worker.uniter.operation hook "install" failed: exit status 1
unit-radarr-xenial-local-0: 00:35:40 ERROR unit.radarr-xenial-local/0.juju-log Could not create group radarr: None
unit-radarr-xenial-local-0: 00:35:40 ERROR unit.radarr-xenial-local/0.juju-log Invalid group radarr being added for user radarr: None
unit-radarr-xenial-local-0: 00:35:49 ERROR unit.radarr-xenial-local/0.juju-log Hook error:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-radarr-xenial-local-0/.venv/lib/python3.5/site-packages/charms/reactive/__init__.py", line 73, in main
    bus.dispatch(restricted=restricted_mode)
  File "/var/lib/juju/agents/unit-radarr-xenial-local-0/.venv/lib/python3.5/site-packages/charms/reactive/bus.py", line 390, in dispatch
    _invoke(other_handlers)
  File "/var/lib/juju/agents/unit-radarr-xenial-local-0/.venv/lib/python3.5/site-packages/charms/reactive/bus.py", line 359, in _invoke
    handler.invoke()
  File "/var/lib/juju/agents/unit-radarr-xenial-local-0/.venv/lib/python3.5/site-packages/charms/reactive/bus.py", line 181, in invoke
    self._action(*args)
  File "/var/lib/juju/agents/unit-radarr-xenial-local-0/charm/reactive/radarr.py", line 31, in install_radarr
    radarr.install_radarr()
  File "lib/lib_radarr.py", line 216, in install_radarr
    self.update_radarr()
  File "lib/lib_radarr.py", line 194, in update_radarr
    self.configure_installdir()
  File "lib/lib_radarr.py", line 178, in configure_installdir
    self.user, chowntopdir=True)
  File "/var/lib/juju/agents/unit-radarr-xenial-local-0/.venv/lib/python3.5/site-packages/charmhelpers/core/host.py", line 908, in chownr
    gid = grp.getgrnam(group).gr_gid
KeyError: 'getgrnam(): name not found: radarr'`

This happens on install of the local but not the jujucharms version of the charms which seems to suggest it's part of this commit.

**Comment by digitalrane** [comment]
OK, worked it out. I was, for no good reason, specifying a uidmap and gidmap in layer.yaml, which causes layer-service-account to try to use a specific UID and GID. On GCE, GID 1001 is the google-sudoers group, so the creation was failing as it couldn't get the requested GID. I added better error handling in the charm in case that happens, but there is also no good reason to specify a UID and GID as the charm by default grabs a free UID and GID when this isn't specified, and the chrownr code in the configure hook takes care of fixing permissions on the Radarr install and configuration directly.

With these changes, I was able to run the full test suite against a GCE model, and all tests passed, including functional and upgrade tests.

Fun fact - this was also broken on GCE prior to this merge! It just didn't error because the chownr wasn't being done - so the missing group was never picked up. Looking at the logs for the charmstore version, you can see it wasn't working previously - 

```
unit-radarr-xenial-jujucharms-0: 19:23:42 DEBUG unit.radarr-xenial-jujucharms/0.juju-log Updated UID for user account radarr to 1001                                                  
unit-radarr-cosmic-jujucharms-0: 19:23:42 INFO unit.radarr-cosmic-jujucharms/0.juju-log Invoking reactive handler: reactive/hostname.py:6:update_hostname                             
unit-radarr-xenial-jujucharms-0: 19:23:42 DEBUG unit.radarr-xenial-jujucharms/0.upgrade-charm usermod: user radarr is currently used by process 17202                                 
unit-radarr-cosmic-jujucharms-0: 19:23:42 INFO unit.radarr-cosmic-jujucharms/0.juju-log Invoking reactive handler: reactive/hostname.py:22:install_layer_hostname                     
unit-radarr-xenial-jujucharms-0: 19:23:42 ERROR unit.radarr-xenial-jujucharms/0.juju-log Invalid or in-use UID 1001 for account radarr: None                                          
unit-radarr-xenial-jujucharms-0: 19:23:42 DEBUG unit.radarr-xenial-jujucharms/0.upgrade-charm groupadd: group 'radarr' already exists
```
So, this merge now also fixed a problem with the charmstore version. Isn't Juju functional testing amazing?

**Comment by digitalrane** [comment]
Also worth noting, a specific UID and GID can still be used, it just has to configured with the `system-uidmap` and `system-gidmap` config.yaml options exposed by layer-service-account, which will override the automatically selectied UID and GID when creating the service user and group.

**Pull request merged**
